name: example
description: Example application.
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies:
  adaptive_dialog:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod:
  flutter_web_plugins:
    sdk: flutter
  go_router:
  mono_kit:
  recase:
  simple_logger:
  url_launcher:
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  go_router_builder:
  pedantic_mono:
dependency_overrides:
  adaptive_dialog:
    path: ..
flutter:
  uses-material-design: true
  assets:
    - assets/images/
