name: example
description: Eample application.
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  adaptive_dialog:
  mono_kit: ^0.16.0-dev
  provider:
  recase:
  simple_logger:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
dependency_overrides:
  adaptive_dialog:
    path: ..
flutter:
  uses-material-design: true