name: adaptive_dialog
description: Show alert dialog or modal action sheet adaptively according to platform.
version: 0.10.0+4
homepage: https://github.com/mono0926/adaptive_dialog
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  animations: ">=2.0.0-nullsafety <3.0.0"
  flutter:
    sdk: flutter
  meta: ">=1.1.8 <2.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
