name: adaptive_dialog
description: Show alert dialog or modal action sheet adaptively according to platform.
version: 1.9.0+2
repository: https://github.com/mono0926/adaptive_dialog
funding:
  - https://github.com/sponsors/mono0926
environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'
dependencies:
  animations: ^2.0.3
  collection: ^1.15.0
  dynamic_color: ^1.4.0
  flutter:
    sdk: flutter
  intersperse: ^2.0.0
  macos_ui: ^2.0.0
  meta: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
screenshots:
  - description: "Adaptive dialog image"
    path: assets/showOkAlertDialog.png
  - description: "Adaptive dialog sample code"
    path: assets/showOkAlertDialog-code.png
topics:
  - dialog
  - ui
  - adaptive
  - alert
  - popup
